name: Renovate

on:
  schedule:
    - cron: "5 12 * * 3"
  workflow_dispatch:
    inputs:
      debug:
        description: "Run Renovate with DEBUG log level"
        required: false
        default: false
        type: boolean

jobs:
  renovate:
    uses: quiquecmtt/reusable-workflows/.github/workflows/renovate.yml@main
    with:
      debug: ${{ inputs.debug || false }}
    secrets:
      RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
